version: 2

models:

  - name: stg_contacts_expected_aww
    columns: 
      - name: contact_phone
        description: primary key for this table
        tests: 
          - not_null
          - unique


  - name: stg_contacts_expected_aws
    columns: 
      - name: contact_phone
        description: primary key for this table
        tests: 
          - not_null
          - unique

  - name: stg_node_configs
    columns: 
      - name: node_label
        description: primary key for this table
        tests: 
          - not_null
          - unique